-- AI-generated daily challenges remain compatible with the existing template publisher.
ALTER TABLE public.challenges
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'template'
  CHECK (source IN ('ai', 'template'));

REVOKE ALL ON FUNCTION public.publish_daily_challenge() FROM anon, authenticated, public;
GRANT EXECUTE ON FUNCTION public.publish_daily_challenge() TO service_role;

-- The app server owns AI generation and inserts with the service role. Clients can only read published rows.
COMMENT ON COLUMN public.challenges.source IS 'Whether this challenge was generated by AI or selected from the vetted template bank.';
